name: First Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1 Step 1
        run: echo "This is Job 1, Step 1"
      - name: Echo Job 1 Step 2
        run: echo "This is Job 1, Step 2"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 2 Step 1
        run: echo "This is Job 2, Step 1"
      - name: Echo Job 2 Step 2
        run: echo "This is Job 2, Step 2"